version: "3.9"

services:
  api:
    container_name: life-game-emulator-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: yarn start:prod
    ports:
      - "${API_PORT}:${API_PORT}"
