name: life-game-emulator-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
        matrix:
          node_version: ['12']
          os: [ubuntu-latest]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: bahmutov/npm-install@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        useLockFile: false

    - name: Installing dependencies
      run: npm i

    - name: Running tests
      run: npm run test
    
    
    
